### ISSUE TITLE
Crear el Loader

### ISSUE THREAD

**Issue by JMCA2805** [Juanjalvarezz/Proyecto_FrontEnd#10]

**Comment by Juanjalvarezz** [comment]
Código y método para implementar el loader
[css.txt](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/files/12112102/css.txt)
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/122636634/7f242900-8b19-4f0d-aa9c-caba71205f90)
