### ISSUE TITLE
Creacion de Mockups

### ISSUE THREAD

**Issue by Juanjalvarezz** [Juanjalvarezz/Proyecto_FrontEnd#15]
Aquí se subirán los mockups para la pagina

**Comment by Aljofranc** [comment]
![smartmockups_lkm32m18](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126708926/fd451d99-c1ca-4b6c-aa3a-bc49ba0ddefd)
![smartmockups_lkm343t7](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126708926/81493981-c2e3-41b0-b937-e88983addadb)

**Comment by Ochoaadev** [comment]
![Mockups 1](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/9c01b5fc-64f7-4233-9b9d-fab45e2fd123)
![Mockups 2](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/590a8afa-d2b1-4e07-9eaa-346aacc84c29)
![Mockups 3](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/0c550b7e-c344-40a9-a0d8-9f94320c1c13)
