### ISSUE TITLE
Propuestas de ideas para el diseño de la pagina

### ISSUE THREAD

**Issue by Juanjalvarezz** [Juanjalvarezz/Proyecto_FrontEnd#4]
Se requieren distintas ideas para el  diseño de la pagina

**Comment by Juanjalvarezz** [comment]
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/122636634/6c503996-d22b-4713-bf99-90e0e9f33ab1)
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/122636634/545927de-d519-4fc6-81bf-91be2253a885)

Ideas

**Comment by YetzeniaM7** [comment]
Mi propuesta es la siguiente:
![photo1689698400](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126374259/b4eef870-5606-4b52-9992-eba915f17486)
![photo1689698486](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126374259/08f9747e-f821-48a2-81d6-952fc11b4f55)
![photo1689698545](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126374259/7a9c0bd0-8e45-465d-8800-b7292c759e2a)

**Comment by JMCA2805** [comment]
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126287724/2864e085-3249-4966-83c0-a0534ff44862)

**Comment by Ochoaadev** [comment]
![Captura de pantalla (152)](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/1b5614ab-e905-492c-bafa-182651819e2c)
![Captura de pantalla (153)](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/7ac5fc0e-84ac-4b8d-9250-937f85572899)
![Captura de pantalla (154)](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/711a34cd-267c-4760-86ca-0aa276712ab7)
![Captura de pantalla (156)](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/efb46030-a71d-47cd-b9dc-ee549f910ac3)

**Comment by Juanjalvarezz** [comment]
Se tomara un poco de cada diseño e ideas personales para la realización de la pagina.
