### ISSUE TITLE
Propuestas de colores para el diseño de la pagina

### ISSUE THREAD

**Issue by Juanjalvarezz** [Juanjalvarezz/Proyecto_FrontEnd#5]
Se requieren distintas ideas para la paleta de colores a usar en el diseño de la pagina

**Comment by Juanjalvarezz** [comment]
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/122636634/77c7d845-e668-4dcc-b170-a563f1b3203c)

Opcion

**Comment by JMCA2805** [comment]
![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126287724/fe23d533-209c-4114-b1ac-8928fdf1e345)

**Comment by YetzeniaM7** [comment]
Mi propuesta
![photo1689698344](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126374259/55962c9a-23aa-4295-bc99-f1a109d6b21b)

**Comment by Aljofranc** [comment]
![Paleta](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/126708926/c6659ac8-373c-475f-b088-322bd5f9d55e)

**Comment by Ochoaadev** [comment]
![Paleta](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/136945432/7ea2e510-86cb-4213-9235-f3bf1a725178)

**Comment by Juanjalvarezz** [comment]
Paleta de colores eleguida:

![Image](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/assets/122636634/e9209b39-e4ac-46ed-9445-0c47991f731f)
