### ISSUE TITLE
Creación de los distintos wireframes para la pagina

### ISSUE THREAD

**Issue by Juanjalvarezz** [Juanjalvarezz/Proyecto_FrontEnd#9]

**Comment by Juanjalvarezz** [comment]
[wireframesJuan.pdf](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/files/12137486/wireframesJuan.pdf)

**Comment by Aljofranc** [comment]
[Wireframes Login Alfonso.pdf](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/files/12149471/Wireframes.Login.Alfonso.pdf)

**Comment by Ochoaadev** [comment]
[WireFrames Adolfo.pdf](https://github.com/Juanjalvarezz/Proyecto_FrontEnd/files/12190257/WireFrames.Adolfo.pdf)
